"""master schedule time columns

Revision ID: 09abe20d256d
Revises: d41c891de5b9
Create Date: 2026-10-01 14:17:12.859488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09abe20d256d'
down_revision: Union[str, Sequence[str], None] = 'd41c891de5b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flex_groups', sa.Column('start_minute', sa.Integer(), nullable=True))
    op.add_column('flex_groups', sa.Column('end_minute', sa.Integer(), nullable=True))
    op.add_column('schedule_entries', sa.Column('start_minute', sa.Integer(), nullable=True))
    op.add_column('schedule_entries', sa.Column('end_minute', sa.Integer(), nullable=True))
    op.add_column('schedule_entries', sa.Column('delivery', sa.String(length=20), nullable=True))
    op.add_column('schedule_entries', sa.Column('block_subject', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schedule_entries', 'block_subject')
    op.drop_column('schedule_entries', 'delivery')
    op.drop_column('schedule_entries', 'end_minute')
    op.drop_column('schedule_entries', 'start_minute')
    op.drop_column('flex_groups', 'end_minute')
    op.drop_column('flex_groups', 'start_minute')
    # ### end Alembic commands ###
