"""creating user to staff combo

Revision ID: 4f4e420a348f
Revises: f2fab530d5a0
Create Date: 2026-07-07 11:53:29.807869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f4e420a348f'
down_revision: Union[str, Sequence[str], None] = 'f2fab530d5a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('staff_members_user_id_fkey'), 'staff_members', type_='foreignkey')
    op.drop_column('staff_members', 'user_id')
    op.add_column('users', sa.Column('staff_id', sa.UUID(), nullable=True))
    op.create_unique_constraint(None, 'users', ['staff_id'])
    op.create_foreign_key(None, 'users', 'staff_members', ['staff_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'staff_id')
    op.add_column('staff_members', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('staff_members_user_id_fkey'), 'staff_members', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
