"""add teacher-student table connections

Revision ID: c5f4fb60c303
Revises: 0eda0df6faf9
Create Date: 2026-07-07 13:03:15.044155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5f4fb60c303'
down_revision: Union[str, Sequence[str], None] = '0eda0df6faf9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_student_teacher', 'student_teachers', ['student_id', 'staff_id'])
    op.create_foreign_key(None, 'student_teachers', 'students', ['student_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'student_teachers', 'staff_members', ['staff_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'student_teachers', type_='foreignkey')
    op.drop_constraint(None, 'student_teachers', type_='foreignkey')
    op.drop_constraint('uq_student_teacher', 'student_teachers', type_='unique')
    # ### end Alembic commands ###
