"""add period_label to schedule_entries and flex_groups

Revision ID: d41c891de5b9
Revises: ef9045513afc
Create Date: 2026-09-16 19:11:04.810601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd41c891de5b9'
down_revision: Union[str, Sequence[str], None] = 'ef9045513afc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flex_groups', sa.Column('period_label', sa.String(length=20), nullable=True))
    op.add_column('schedule_entries', sa.Column('period_label', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schedule_entries', 'period_label')
    op.drop_column('flex_groups', 'period_label')
    # ### end Alembic commands ###
