"""initial schema

Revision ID: f2fab530d5a0
Revises: 
Create Date: 2026-06-30 20:22:14.907157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f2fab530d5a0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schools',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('district_name', sa.String(length=255), nullable=True),
    sa.Column('timezone', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('legal_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('rule_type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('rule_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schedule_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('school_year', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('generated_by', sa.String(length=255), nullable=True),
    sa.Column('summary_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('students',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('external_student_id', sa.String(length=100), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('grade', sa.String(length=50), nullable=True),
    sa.Column('homeroom', sa.String(length=100), nullable=True),
    sa.Column('has_iep', sa.Boolean(), nullable=False),
    sa.Column('enl_level', sa.String(length=50), nullable=True),
    sa.Column('enl_minutes_required', sa.Integer(), nullable=False),
    sa.Column('mtss_tier', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_students_external_id', 'students', ['school_id', 'external_student_id'], unique=False)
    op.create_index('idx_students_school_grade', 'students', ['school_id', 'grade'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('approval_actions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('user_name', sa.String(length=255), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['schedule_runs.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=True),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('before_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('staff_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('external_staff_id', sa.String(length=100), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('grade', sa.String(length=50), nullable=True),
    sa.Column('homeroom', sa.String(length=100), nullable=True),
    sa.Column('room', sa.String(length=100), nullable=True),
    sa.Column('is_certified_sped', sa.Boolean(), nullable=False),
    sa.Column('is_certified_enl', sa.Boolean(), nullable=False),
    sa.Column('is_certified_slp', sa.Boolean(), nullable=False),
    sa.Column('can_deliver_setss', sa.Boolean(), nullable=False),
    sa.Column('max_students_per_group', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_staff_school_grade', 'staff_members', ['school_id', 'grade'], unique=False)
    op.create_index('idx_staff_school_title', 'staff_members', ['school_id', 'title'], unique=False)
    op.create_table('compliance_flags',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=True),
    sa.Column('staff_id', sa.UUID(), nullable=True),
    sa.Column('student_external_id', sa.String(length=100), nullable=True),
    sa.Column('teacher_name', sa.String(length=255), nullable=True),
    sa.Column('flag_type', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('legal_reference', sa.Text(), nullable=True),
    sa.Column('affected_period', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['schedule_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['staff_members.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('flex_groups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('tier', sa.String(length=50), nullable=True),
    sa.Column('focus_area', sa.String(length=100), nullable=True),
    sa.Column('staff_id', sa.UUID(), nullable=True),
    sa.Column('teacher_name', sa.String(length=255), nullable=True),
    sa.Column('day_of_week', sa.String(length=20), nullable=True),
    sa.Column('period', sa.Integer(), nullable=True),
    sa.Column('max_group_size', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['schedule_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['staff_members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schedule_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('staff_id', sa.UUID(), nullable=True),
    sa.Column('student_external_id', sa.String(length=100), nullable=True),
    sa.Column('student_name', sa.String(length=255), nullable=True),
    sa.Column('grade', sa.String(length=50), nullable=True),
    sa.Column('teacher_name', sa.String(length=255), nullable=True),
    sa.Column('day_of_week', sa.String(length=20), nullable=False),
    sa.Column('period', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('room', sa.String(length=100), nullable=True),
    sa.Column('service_type', sa.String(length=100), nullable=True),
    sa.Column('is_pullout', sa.Boolean(), nullable=False),
    sa.Column('is_flex_period', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['schedule_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['staff_members.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'student_id', 'day_of_week', 'period', name='uq_student_one_entry_per_slot_per_run')
    )
    op.create_index('idx_schedule_run_grade', 'schedule_entries', ['run_id', 'grade'], unique=False)
    op.create_index('idx_schedule_run_staff', 'schedule_entries', ['run_id', 'staff_id'], unique=False)
    op.create_index('idx_schedule_run_student', 'schedule_entries', ['run_id', 'student_id'], unique=False)
    op.create_index('idx_schedule_student_slot', 'schedule_entries', ['run_id', 'student_id', 'day_of_week', 'period'], unique=False)
    op.create_index('idx_schedule_teacher_slot', 'schedule_entries', ['run_id', 'staff_id', 'day_of_week', 'period'], unique=False)
    op.create_table('student_services',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('service_type', sa.String(length=100), nullable=False),
    sa.Column('subject_area', sa.String(length=100), nullable=True),
    sa.Column('minutes_per_week', sa.Integer(), nullable=False),
    sa.Column('sessions_per_week', sa.Integer(), nullable=True),
    sa.Column('is_pullout', sa.Boolean(), nullable=False),
    sa.Column('preferred_provider_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['preferred_provider_id'], ['staff_members.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_student_services_student', 'student_services', ['student_id'], unique=False)
    op.create_index('idx_student_services_type', 'student_services', ['school_id', 'service_type'], unique=False)
    op.create_table('flex_group_students',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('flex_group_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['flex_group_id'], ['flex_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('flex_group_id', 'student_id', name='uq_flex_group_student')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('flex_group_students')
    op.drop_index('idx_student_services_type', table_name='student_services')
    op.drop_index('idx_student_services_student', table_name='student_services')
    op.drop_table('student_services')
    op.drop_index('idx_schedule_teacher_slot', table_name='schedule_entries')
    op.drop_index('idx_schedule_student_slot', table_name='schedule_entries')
    op.drop_index('idx_schedule_run_student', table_name='schedule_entries')
    op.drop_index('idx_schedule_run_staff', table_name='schedule_entries')
    op.drop_index('idx_schedule_run_grade', table_name='schedule_entries')
    op.drop_table('schedule_entries')
    op.drop_table('flex_groups')
    op.drop_table('compliance_flags')
    op.drop_index('idx_staff_school_title', table_name='staff_members')
    op.drop_index('idx_staff_school_grade', table_name='staff_members')
    op.drop_table('staff_members')
    op.drop_table('audit_logs')
    op.drop_table('approval_actions')
    op.drop_table('users')
    op.drop_index('idx_students_school_grade', table_name='students')
    op.drop_index('idx_students_external_id', table_name='students')
    op.drop_table('students')
    op.drop_table('schedule_runs')
    op.drop_table('legal_rules')
    op.drop_table('schools')
    # ### end Alembic commands ###
